### ISSUE TITLE
[FEEDER] DE is down

### ISSUE THREAD

**Issue by corradio** [corradio/electricitymap#88]
```
Traceback (most recent call last):
  File "feeder/parsers/DE.py", line 43, in <module>
    print fetch_DE()
  File "feeder/parsers/DE.py", line 21, in fetch_DE
    'datetime': arrow.get(parsed['wind'][0] / 1000.0).datetime, # UTC
KeyError: 'wind'
```

Body of HTTP response shows
`<div class="tx-agora-graphs tx-agora-graphs-graph" >\n\t\n\n\t\t\n\t\t\t\t<div class="graph-message">No data available. Please try again later.</div>\n\t\t\t\n\t\n\n\n\n</div>`

**Comment by corradio** [comment]
Nothing do to, it seems that DE has no data for the last two days. :(
